title: Amrita H Nair
email: amritahnair@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Amrita Nair's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: amrtanair
github_username:  amrtanair

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

