title: Amrita H Nair
email: amritahnair@gmail.com
description: Amrita Nair's blog
baseurl: ""
url: "https://amrtanair.github.io/"

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - background.md
  - blog.md
  - tags.md
  - index.md
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-pdf-embed
  - jemoji

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag
  permalinks:
    tag: /tags/:name/

excerpt_separator: <!--more-->

twitter: amrtanair
github: amrtanair